import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:sparkle_lite/core/constants/app_theme.dart';
import 'package:sparkle_lite/providers/theme_provider.dart';
import 'package:sparkle_lite/routers/app_router.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

/// Main entry point of the Sparkle Lite app
/// This file initializes the app, sets up the main widget, and configures the router for navigating between different screens. It also initializes shared preferences to ensure that any necessary data is loaded before the app starts. The MyApp widget defines the overall theme and appearance of the app, including color schemes, typography, and input decoration styles. By using MaterialApp.router, it integrates the GoRouter for handling navigation in a clean and efficient way. This setup allows for a smooth user experience as users navigate through the various features of Sparkle Lite, such as onboarding, dashboard, symptom logging, and health record management. Overall, this file serves as the foundation for the entire app, ensuring that all necessary configurations are in place for a seamless user experience.

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase 
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  await SharedPreferences.getInstance();
  
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch the theme mode provider to rebuild when theme changes
    final themeMode = ref.watch(appThemeModeProvider);
    
    return MaterialApp.router(
      title: 'Sparkle Lite',
      debugShowCheckedModeBanner: false,
      routerConfig: appRouter,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeMode,
    );
  }
}