import 'package:equatable/equatable.dart';

/// AIInsight model representing insights generated by the AI based on user's symptoms and records.
/// This is a non-diagnostic, informational model meant to provide users with potential patterns and guidance based on their logged data.
class AIInsight extends Equatable {
  final String id;
  final String userId;
  final String summary;
  final String possiblePattern;
  final String careGuidance;
  final List<String> doctorQuestions;
  final String disclaimer;
  final DateTime createdAt;
  final List<String> symptomsAnalyzed;
  final int symptomsCount;

  const AIInsight({
    required this.id,
    required this.userId,
    required this.summary,
    required this.possiblePattern,
    required this.careGuidance,
    required this.doctorQuestions,
    required this.disclaimer,
    required this.createdAt,
    required this.symptomsAnalyzed,
    required this.symptomsCount,
  });

  
  static const String safeDisclaimer = 
      "This is not a diagnosis and does not replace medical advice. "
      "Always consult with a healthcare provider for medical concerns.";

  @override
  List<Object?> get props => [id, userId, createdAt];

  // Convert to JSON for storage
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'summary': summary,
      'possiblePattern': possiblePattern,
      'careGuidance': careGuidance,
      'doctorQuestions': doctorQuestions,
      'disclaimer': disclaimer,
      'createdAt': createdAt.toIso8601String(),
      'symptomsAnalyzed': symptomsAnalyzed,
      'symptomsCount': symptomsCount,
    };
  }

  // Create from JSON
  factory AIInsight.fromJson(Map<String, dynamic> json) {
    return AIInsight(
      id: json['id'],
      userId: json['userId'],
      summary: json['summary'],
      possiblePattern: json['possiblePattern'],
      careGuidance: json['careGuidance'],
      doctorQuestions: List<String>.from(json['doctorQuestions']),
      disclaimer: json['disclaimer'],
      createdAt: DateTime.parse(json['createdAt']),
      symptomsAnalyzed: List<String>.from(json['symptomsAnalyzed']),
      symptomsCount: json['symptomsCount'],
    );
  }
}